### ISSUE TITLE
Add sites_cultivars relationships for seasons 1 and 2

### ISSUE THREAD

**Issue by dlebauer** [terraref/reference-data#135]
Need to add sites_cultivars relationships for seasons 1 and 2

### TODO

* [x] Run script for season 2 https://gist.github.com/dlebauer/a5d3b72485449f7c8fed1657b1666887
* [x] generate and run similar script for season 1 

### Completion Criteria

* [x] `select * from traits where cultivar_id = null` retuns 0 records

**Comment by dlebauer** [comment]
* Season 1 https://gist.github.com/dlebauer/cb1b96ba8b5c3c8c600e74ceb40aed3d

Deleting duplicates

```sql
DELETE FROM sites_cultivars 
WHERE id IN (SELECT id
              FROM (SELECT id,
                             ROW_NUMBER() OVER (partition BY site_id, cultivar_id ORDER BY id) AS rnum
                     FROM sites_cultivars ) t
              WHERE t.rnum > 1);
```
