### ISSUE TITLE
Shiny App for Trait Data Visualization

### ISSUE THREAD

**Issue by nheyek** [terraref/reference-data#142]
### Description
A web interface for visualizing trait data from BETYdb.
Visualizations will be available for all variables measured in a given experiment/season.
Multiple experiments/seasons will be available to visualize data from.
The web app will be available to view from a public domain.
Feedback will be collected to improve the app.

### Completion Criteria
- [x] Get Feedback on Prototype Flask App
- [x] Create Basic Framework for Shiny App
- [x] Create Basic Visualizations for Traits within a Given Season (Partial Data)
- [x] Get App Working with Full BETYdb Data Sets
- [x] Upgrade Visualizations
- [x] Deploy Shiny App
- [x] Get Feedback on Shiny App
- [x] Reformat Experiments/Seasons Menu
- [x] Implement Subsetting by Cultivar/Genotype
- [x] Reconfigure Caching Functionality
- [x] Clean Up Plots
- [x] Implement Field Scale Heat Maps

**Comment by dlebauer** [comment]
Available at traitvis.workbench.terraref.org
